name: check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      # Prepare
      - uses: Kesin11/actions-timeline@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Show environment
        run: pwd; ls -la; node -v; npm -v

      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check
